-- https://en.wikipedia.org/wiki/List_of_GameCube_games

INSERT INTO platforms(id, name)
VALUES (1, 'GameCube');

INSERT INTO games(name, platform_id)
VALUES ('1080° Avalanche', 1)
     , ('18 Wheeler: American Pro Trucker', 1)
     , ('2002 FIFA World Cup', 1)
     , ('2006 FIFA World Cup', 1)
     , ('4x4 EVO 2', 1)
     , ('The Adventures of Jimmy Neutron Boy Genius: Attack of the Twonkies', 1)
     , ('The Adventures of Jimmy Neutron Boy Genius: Jet Fusion', 1)
     , ('Aggressive Inline', 1)
     , ('Alien Hominid', 1)
     , ('All-Star Baseball 2002', 1)
     , ('All-Star Baseball 2003', 1)
     , ('All-Star Baseball 2004', 1)
     , ('Amazing Island', 1)
     , ('American Chopper 2: Full Throttle', 1)
     , ('Animal Crossing', 1)
     , ('Animaniacs: The Great Edgar Hunt', 1)
     , ('The Ant Bully', 1)
     , ('Aquaman: Battle for Atlantis', 1)
     , ('Army Men: Air Combat - The Elite Missions', 1)
     , ('Army Men RTS: Real Time Strategy', 1)
     , ('Army Men: Sarge''s War', 1)
     , ('Asterix &amp; Obelix XXL', 1)
     , ('ATV: Quad Power Racing 2', 1)
     , ('Auto Modellista', 1)
     , ('Avatar: The Last Airbender', 1)
     , ('Backyard Baseball', 1)
     , ('Backyard Baseball 2007', 1)
     , ('Backyard Football', 1)
     , ('Bad Boys: Miami Takedown', 1)
     , ('Baldur''s Gate: Dark Alliance', 1)
     , ('Barnyard', 1)
     , ('The Baseball 2003', 1)
     , ('Baten Kaitos: Eternal Wings and the Lost Ocean', 1)
     , ('Baten Kaitos Origins', 1)
     , ('Batman Begins', 1)
     , ('Batman: Vengeance', 1)
     , ('Batman: Dark Tomorrow', 1)
     , ('Batman: Rise of Sin Tzu', 1)
     , ('Battalion Wars', 1)
     , ('Battle Stadium D.O.N', 1)
     , ('Beach Spikers', 1)
     , ('Beyblade VForce: Super Tournament Battle', 1)
     , ('Beyond Good &amp; Evil', 1)
     , ('Big Air Freestyle', 1)
     , ('Big Mutha Truckers', 1)
     , ('Billy Hatcher and the Giant Egg', 1)
     , ('Bionicle', 1)
     , ('Bionicle Heroes', 1)
     , ('Black &amp; Bruised', 1)
     , ('Bleach GC: Tasogare Ni Mamieru Shinigami', 1)
     , ('Blood Omen 2', 1)
     , ('BloodRayne', 1)
     , ('Bloody Roar: Primal Fury', 1)
     , ('BlowOut', 1)
     , ('BMX XXX', 1)
     , ('Bobobo-bo Bo-bobo Dassutsu! Hajike Royale', 1)
     , ('Bokujou Monogatari: Shiawase no Uta', 1)
     , ('Bomberman Generation', 1)
     , ('Bomberman Jetters', 1)
     , ('Bomberman Land 2', 1)
     , ('Bratz: Forever Diamondz', 1)
     , ('Bratz: Rock Angelz', 1)
     , ('Buffy the Vampire Slayer: Chaos Bleeds', 1)
     , ('Burnout', 1)
     , ('Burnout 2: Point of Impact', 1)
     , ('Bust-a-Move 3000', 1)
     , ('Butt-Ugly Martians: Zoom or Doom', 1)
     , ('Cabela''s Big Game Hunter 2005 Adventures', 1)
     , ('Cabela''s Dangerous Hunts 2', 1)
     , ('Cabela''s Outdoor Adventures', 1)
     , ('Call of Duty 2: Big Red One', 1)
     , ('Call of Duty: Finest Hour', 1)
     , ('Capcom vs. SNK 2 EO', 1)
     , ('Captain Tsubasa: Ōgon Sedai no Chōsen', 1)
     , ('Carmen Sandiego: The Secret of the Stolen Drums', 1)
     , ('Cars', 1)
     , ('Casper: Spirit Dimensions', 1)
     , ('Catwoman', 1)
     , ('Cel Damage', 1)
     , ('Chaos Field', 1)
     , ('Charinko Hero', 1)
     , ('Charlie and the Chocolate Factory', 1)
     , ('Charlie''s Angels', 1)
     , ('Chibi-Robo!', 1)
     , ('Chicken Little', 1)
     , ('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 1)
     , ('City Racer', 1)
     , ('Cocoto Funfair', 1)
     , ('Cocoto Kart Racer', 1)
     , ('Cocoto Platform Jumper', 1)
     , ('Codename: Kids Next Door – Operation: V.I.D.E.O.G.A.M.E.', 1)
     , ('Conan', 1)
     , ('Conflict: Desert Storm', 1)
     , ('Conflict: Desert Storm II - Back to Baghdad', 1)
     , ('Crash Bandicoot: The Wrath of Cortex', 1)
     , ('Crash Nitro Kart', 1)
     , ('Crash Tag Team Racing', 1)
     , ('Crazy Taxi', 1)
     , ('Cubivore: Survival of the Fittest', 1)
     , ('Cubix Robots for Everyone: Showdown', 1)
     , ('Curious George', 1)
     , ('Custom Robo', 1)
     , ('Dakar 2: The World''s Ultimate Rally', 1)
     , ('Dance Dance Revolution Mario Mix', 1)
     , ('Dark Summit', 1)
     , ('Darkened Skye', 1)
     , ('Dave Mirra Freestyle BMX 2', 1)
     , ('Dead to Rights', 1)
     , ('Def Jam Vendetta', 1)
     , ('Def Jam: Fight for NY', 1)
     , ('Defender', 1)
     , ('Derby Tsuku 3: Derby Uma o Tsukurou!', 1)
     , ('Die Hard: Vendetta', 1)
     , ('Digimon Rumble Arena 2', 1)
     , ('Digimon World 4', 1)
     , ('Dinotopia: The Sunstone Odyssey', 1)
     , ('Disney Sports Basketball', 1)
     , ('Disney Sports Football', 1)
     , ('Disney Sports Skateboarding', 1)
     , ('Disney Sports Soccer', 1)
     , ('Disney''s Extreme Skate Adventure', 1)
     , ('Disney''s Hide &amp; Sneak', 1)
     , ('Disney''s Magical Mirror Starring Mickey Mouse', 1)
     , ('Disney''s Party', 1)
     , ('Disney''s PK: Out of the Shadows', 1)
     , ('Disney''s Tarzan: Untamed', 1)
     , ('Dokapon DX: Wataru Sekai wa Oni Darake', 1)
     , ('Donald Duck: Goin'' Quackers', 1)
     , ('Donkey Kong Jungle Beat', 1)
     , ('Donkey Konga', 1)
     , ('Donkey Konga 2', 1)
     , ('Donkey Konga 3', 1)
     , ('Dora the Explorer: Journey to the Purple Planet', 1)
     , ('Doraemon: Minna de Asobo! Minidorando', 1)
     , ('Doshin the Giant', 1)
     , ('Doubutsu no Mori e+', 1)
     , ('Dr. Muto', 1)
     , ('Dragon Ball Z: Budokai', 1)
     , ('Dragon Ball Z: Budokai 2', 1)
     , ('Dragon Ball Z: Sagas', 1)
     , ('Dragon Drive: D-Masters Shot', 1)
     , ('Dragon''s Lair 3D: Return to the Lair', 1)
     , ('DreamMix TV World Fighters', 1)
     , ('Driven', 1)
     , ('Drome Racers', 1)
     , ('Duel Masters: Nettō! Battle Arena', 1)
     , ('Ed, Edd n Eddy: The Mis-Edventures', 1)
     , ('Egg Mania: Eggstreme Madness', 1)
     , ('Eisei Meijin VI', 1)
     , ('Enter the Matrix', 1)
     , ('ESPN International Winter Sports 2002', 1)
     , ('ESPN MLS ExtraTime 2002', 1)
     , ('Eternal Darkness: Sanity''s Requiem', 1)
     , ('Evolution Skateboarding', 1)
     , ('Evolution Snowboarding', 1)
     , ('Evolution Worlds', 1)
     , ('Extreme-G 3', 1)
     , ('F-Zero GX', 1)
     , ('F1 2002', 1)
     , ('F1 Career Challenge', 1)
     , ('The Fairly OddParents: Breakin'' Da Rules', 1)
     , ('The Fairly OddParents: Shadow Showdown', 1)
     , ('Family Stadium 2003', 1)
     , ('Fantastic 4', 1)
     , ('FIFA Soccer 06', 1)
     , ('FIFA Soccer 07', 1)
     , ('FIFA Soccer 2002', 1)
     , ('FIFA Soccer 2003', 1)
     , ('FIFA Soccer 2004', 1)
     , ('FIFA Soccer 2005', 1)
     , ('FIFA Street', 1)
     , ('FIFA Street 2', 1)
     , ('Fight Night Round 2', 1)
     , ('Final Fantasy Crystal Chronicles', 1)
     , ('Finding Nemo', 1)
     , ('Fire Blade', 1)
     , ('Fire Emblem: Path of Radiance', 1)
     , ('Flushed Away', 1)
     , ('Franklin: A Birthday Surprise', 1)
     , ('Freaky Flyers', 1)
     , ('Freedom Fighters', 1)
     , ('Freekstyle', 1)
     , ('Freestyle MetalX', 1)
     , ('Freestyle Street Soccer', 1)
     , ('Frogger: Ancient Shadow', 1)
     , ('Frogger Beyond', 1)
     , ('Frogger''s Adventures: The Rescue', 1)
     , ('From Russia with Love', 1)
     , ('Future Tactics: The Uprising', 1)
     , ('Gakuen Toshi Vara Noir', 1)
     , ('Gauntlet: Dark Legacy', 1)
     , ('Geist', 1)
     , ('Gekitō Pro Yakyū', 1)
     , ('Generation of Chaos Exceed', 1)
     , ('GiFTPiA', 1)
     , ('Gladius', 1)
     , ('Go! Go! Hypergrind', 1)
     , ('Goblin Commander: Unleash the Horde', 1)
     , ('Godzilla: Destroy All Monsters Melee', 1)
     , ('GoldenEye: Rogue Agent', 1)
     , ('Gotcha Force', 1)
     , ('The Grim Adventures of Billy &amp; Mandy', 1)
     , ('Grooverider: Slot Car Thunder', 1)
     , ('GT Cube', 1)
     , ('GUN', 1)
     , ('Happy Feet', 1)
     , ('Harry Potter and the Chamber of Secrets', 1)
     , ('Harry Potter and the Goblet of Fire', 1)
     , ('Harry Potter and the Sorcerer''s Stone', 1)
     , ('Harry Potter and the Prisoner of Azkaban', 1)
     , ('Harry Potter: Quidditch World Cup', 1)
     , ('Harvest Moon: A Wonderful Life', 1)
     , ('Harvest Moon: Another Wonderful Life', 1)
     , ('Harvest Moon: Magical Melody', 1)
     , ('The Haunted Mansion', 1)
     , ('Hello Kitty: Roller Rescue', 1)
     , ('Hikaru no Go 3', 1)
     , ('Hitman 2: Silent Assassin', 1)
     , ('The Hobbit', 1)
     , ('Home Run King', 1)
     , ('Homeland', 1)
     , ('Hot Wheels Velocity X', 1)
     , ('Hot Wheels World Race', 1)
     , ('Hulk', 1)
     , ('Hunter: The Reckoning', 1)
     , ('I-Ninja', 1)
     , ('Ice Age 2: The Meltdown', 1)
     , ('Ikaruga', 1)
     , ('The Incredible Hulk: Ultimate Destruction', 1)
     , ('The Incredibles', 1)
     , ('The Incredibles: Rise of the Underminer', 1)
     , ('Intellivision Lives!', 1)
     , ('International Superstar Soccer 2', 1)
     , ('International Superstar Soccer 3', 1)
     , ('The Italian Job', 1)
     , ('James Bond 007: Everything or Nothing', 1)
     , ('James Bond 007: Agent Under Fire', 1)
     , ('James Bond 007: NightFire', 1)
     , ('Jeremy McGrath Supercross World', 1)
     , ('Jikkyou Powerful Major League', 1)
     , ('Jikkyou Powerful Pro Yakyuu 10', 1)
     , ('Jikkyou Powerful Pro Yakyuu 10 Chou Ketteiban', 1)
     , ('Jikkyou Powerful Pro Yakyuu 11', 1)
     , ('Jikkyou Powerful Pro Yakyuu 11 Chou Ketteiban', 1)
     , ('Jikkyou Powerful Pro Yakyuu 12', 1)
     , ('Jikkyou Powerful Pro Yakyuu 12 Ketteiban', 1)
     , ('Jikkyou Powerful Pro Yakyuu 9', 1)
     , ('Jikkyou Powerful Pro Yakyuu 9 Ketteiban', 1)
     , ('Jikkyō World Soccer 2002', 1)
     , ('Jimmy Neutron: Boy Genius', 1)
     , ('Judge Dredd: Dredd Vs. Death', 1)
     , ('Kao the Kangaroo Round 2', 1)
     , ('Karaoke Revolution Party', 1)
     , ('Kelly Slater''s Pro Surfer', 1)
     , ('Kidō Senshi Gundam: Gundam vs. Z Gundam', 1)
     , ('Kidō Senshi Gundam: Senshitachi no Kiseki', 1)
     , ('Killer7', 1)
     , ('King Arthur', 1)
     , ('Kirby Air Ride', 1)
     , ('Kiwame Mahjong DX2', 1)
     , ('Knights of the Temple: Infernal Crusade', 1)
     , ('Knockout Kings 2003', 1)
     , ('Konjiki no Gash Bell!! Yūjō no Tag Battle Full Power', 1)
     , ('Konjiki no Gash Bell!! Go! Go! Mamono Fight!!', 1)
     , ('Korokke! Ban-Ō no Kiki o Sukue', 1)
     , ('Kururin Squash!', 1)
     , ('Largo Winch: Empire Under Threat', 1)
     , ('Legend of Golfer', 1)
     , ('The Legend of Spyro: A New Beginning', 1)
     , ('The Legend of Zelda: Collector''s Edition', 1)
     , ('The Legend of Zelda: Four Swords Adventures', 1)
     , ('The Legend of Zelda: Ocarina of Time / Master Quest', 1)
     , ('The Legend of Zelda: Twilight Princess', 1)
     , ('The Legend of Zelda: The Wind Waker', 1)
     , ('Legends of Wrestling', 1)
     , ('Legends of Wrestling II', 1)
     , ('Lego Star Wars: The Video Game', 1)
     , ('Lego Star Wars II: The Original Trilogy', 1)
     , ('Lemony Snicket''s A Series of Unfortunate Events', 1)
     , ('Looney Tunes: Back in Action', 1)
     , ('The Lord of the Rings: The Return of the King', 1)
     , ('The Lord of the Rings: The Third Age', 1)
     , ('The Lord of the Rings: The Two Towers', 1)
     , ('Lost Kingdoms', 1)
     , ('Lost Kingdoms II', 1)
     , ('Lotus Challenge', 1)
     , ('Luigi''s Mansion', 1)
     , ('Lupin Sansei: Umi ni Kieta Hihou', 1)
     , ('Madagascar', 1)
     , ('Madden NFL 2002', 1)
     , ('Madden NFL 2003', 1)
     , ('Madden NFL 2004', 1)
     , ('Madden NFL 2005', 1)
     , ('Madden NFL 06', 1)
     , ('Madden NFL 07', 1)
     , ('Madden NFL 08', 1)
     , ('Major League Baseball 2K6', 1)
     , ('Mario Golf: Toadstool Tour', 1)
     , ('Mario Kart: Double Dash!!', 1)
     , ('Mario Party 4', 1)
     , ('Mario Party 5', 1)
     , ('Mario Party 6', 1)
     , ('Mario Party 7', 1)
     , ('Mario Power Tennis', 1)
     , ('Mario Superstar Baseball', 1)
     , ('Mark Davis Pro Bass Challenge', 1)
     , ('Marvel Nemesis: Rise of the Imperfects', 1)
     , ('Mary-Kate and Ashley: Sweet 16 – Licensed to Drive', 1)
     , ('Mat Hoffman''s Pro BMX 2', 1)
     , ('MC Groovz Dance Craze', 1)
     , ('Medabots Infinity', 1)
     , ('Medal of Honor: European Assault', 1)
     , ('Medal of Honor: Frontline', 1)
     , ('Medal of Honor: Rising Sun', 1)
     , ('Meet the Robinsons', 1)
     , ('Mega Man Anniversary Collection', 1)
     , ('Mega Man Network Transmission', 1)
     , ('Mega Man X Collection', 1)
     , ('Mega Man X: Command Mission', 1)
     , ('Men in Black II: Alien Escape', 1)
     , ('Mercedes-Benz World Racing', 1)
     , ('Metal Arms: Glitch in the System', 1)
     , ('Metal Gear Solid: The Twin Snakes', 1)
     , ('Metal Gear Solid: The Twin Snakes Special Disc', 1)
     , ('Metroid Prime', 1)
     , ('Metroid Prime 2: Echoes', 1)
     , ('Micro Machines', 1)
     , ('Midway Arcade Treasures', 1)
     , ('Midway Arcade Treasures 2', 1)
     , ('Midway Arcade Treasures 3', 1)
     , ('Minority Report: Everybody Runs', 1)
     , ('Mission: Impossible - Operation Surma', 1)
     , ('MLB Slugfest 20-03', 1)
     , ('MLB Slugfest 20-04', 1)
     , ('Momotarō Dentetsu 11: Black Bombee Shutsugen! No Maki', 1)
     , ('Momotarō Dentetsu 12: Nishinihon Hen mo ari Masse!', 1)
     , ('Monopoly Party', 1)
     , ('Monster 4x4: Masters of Metal', 1)
     , ('Monster House', 1)
     , ('Monster Jam: Maximum Destruction', 1)
     , ('Monsters, Inc. Scream Arena', 1)
     , ('Mortal Kombat: Deadly Alliance', 1)
     , ('Mortal Kombat: Deception', 1)
     , ('Mr. Driller: Drill Land', 1)
     , ('Muppets Party Cruise', 1)
     , ('Mutsu to Nohohon', 1)
     , ('MVP Baseball 2004', 1)
     , ('MVP Baseball 2005', 1)
     , ('MX Superfly', 1)
     , ('Mystic Heroes', 1)
     , ('Namco Museum', 1)
     , ('Namco Museum 50th Anniversary', 1)
     , ('Naruto: Clash of Ninja', 1)
     , ('Naruto: Clash of Ninja 2', 1)
     , ('Naruto: Gekitō Ninja Taisen! 3', 1)
     , ('Naruto: Gekitō Ninja Taisen! 4', 1)
     , ('NASCAR 2005: Chase for the Cup', 1)
     , ('NASCAR Thunder 2003', 1)
     , ('NASCAR: Dirt to Daytona', 1)
     , ('NBA 2K2', 1)
     , ('NBA 2K3', 1)
     , ('NBA Courtside 2002', 1)
     , ('NBA Live 2003', 1)
     , ('NBA Live 2004', 1)
     , ('NBA Live 2005', 1)
     , ('NBA Live 06', 1)
     , ('NBA Street', 1)
     , ('NBA Street Vol. 2', 1)
     , ('NBA Street V3', 1)
     , ('NCAA College Basketball 2K3', 1)
     , ('NCAA College Football 2K3', 1)
     , ('NCAA Football 2003', 1)
     , ('NCAA Football 2004', 1)
     , ('NCAA Football 2005', 1)
     , ('Need for Speed: Carbon', 1)
     , ('Need for Speed: Hot Pursuit 2', 1)
     , ('Need for Speed: Most Wanted', 1)
     , ('Need for Speed: Underground', 1)
     , ('Need for Speed: Underground 2', 1)
     , ('Neighbours from Hell', 1)
     , ('NFL 2K3', 1)
     , ('NFL Blitz 20-02', 1)
     , ('NFL Blitz 20-03', 1)
     , ('NFL Blitz Pro', 1)
     , ('NFL Quarterback Club 2002', 1)
     , ('NFL Street', 1)
     , ('NFL Street 2', 1)
     , ('NHL 2003', 1)
     , ('NHL 2004', 1)
     , ('NHL 2005', 1)
     , ('NHL 06', 1)
     , ('NHL 2K3', 1)
     , ('NHL Hitz 20-02', 1)
     , ('NHL Hitz 20-03', 1)
     , ('NHL Hitz Pro', 1)
     , ('Nickelodeon Party Blast', 1)
     , ('Nicktoons: Battle for Volcano Island', 1)
     , ('Nicktoons Unite!', 1)
     , ('Nintendo Puzzle Collection', 1)
     , ('Odama', 1)
     , ('Ohenro-San', 1)
     , ('One Piece: Grand Adventure', 1)
     , ('One Piece: Grand Battle! 3', 1)
     , ('One Piece: Grand Battle! Rush', 1)
     , ('One Piece: Pirates'' Carnival', 1)
     , ('One Piece: Treasure Battle!', 1)
     , ('Open Season', 1)
     , ('Outlaw Golf', 1)
     , ('Over the Hedge', 1)
     , ('P.N.03', 1)
     , ('Pac-Man Fever', 1)
     , ('Pac-Man Vs.', 1)
     , ('Pac-Man World 2', 1)
     , ('Pac-Man World 3', 1)
     , ('Pac-Man World Rally', 1)
     , ('Paper Mario: The Thousand-Year Door', 1)
     , ('Peter Jackson''s King Kong: The Official Game of the Movie', 1)
     , ('Phantasy Star Online Episode I &amp; II', 1)
     , ('Phantasy Star Online Episode I &amp; II Plus', 1)
     , ('Phantasy Star Online Episode III: C.A.R.D. Revolution', 1)
     , ('Piglet''s Big Game', 1)
     , ('Pikmin', 1)
     , ('Pikmin 2', 1)
     , ('Pinball Hall of Fame: The Gottlieb Collection', 1)
     , ('Pitfall: The Lost Expedition', 1)
     , ('Pokémon Box: Ruby and Sapphire', 1)
     , ('Pokémon Channel', 1)
     , ('Pokémon Colosseum', 1)
     , ('Pokémon XD: Gale of Darkness', 1)
     , ('The Polar Express', 1)
     , ('Pool Edge', 1)
     , ('Pool Paradise', 1)
     , ('Power Rangers: Dino Thunder', 1)
     , ('The Powerpuff Girls: Relish Rampage - Pickled Edition', 1)
     , ('Prince of Persia: The Sands of Time', 1)
     , ('Prince of Persia: The Two Thrones', 1)
     , ('Prince of Persia: Warrior Within', 1)
     , ('Pro Rally', 1)
     , ('Puyo Pop Fever', 1)
     , ('R: Racing Evolution', 1)
     , ('Radirgy GeneriC', 1)
     , ('Rally Championship', 1)
     , ('Rampage: Total Destruction', 1)
     , ('Ratatouille', 1)
     , ('Rave Master', 1)
     , ('Rayman 3: Hoodlum Havoc', 1)
     , ('Rayman Arena', 1)
     , ('Red Faction II', 1)
     , ('RedCard 20-03', 1)
     , ('Rei Fighter Gekitsui Senki', 1)
     , ('Reign of Fire', 1)
     , ('Resident Evil', 1)
     , ('Resident Evil 2', 1)
     , ('Resident Evil 3: Nemesis', 1)
     , ('Resident Evil 4', 1)
     , ('Resident Evil - Code: Veronica', 1)
     , ('Resident Evil Zero', 1)
     , ('Ribbit King', 1)
     , ('Road Trip: The Arcade Edition', 1)
     , ('RoadKill', 1)
     , ('RoboCop', 1)
     , ('Robotech: Battlecry', 1)
     , ('Robots', 1)
     , ('Rocket Power: Beach Bandits', 1)
     , ('Rocky', 1)
     , ('Rogue Ops', 1)
     , ('Rugrats: Royal Ransom', 1)
     , ('Samurai Jack: The Shadow of Aku', 1)
     , ('Scaler', 1)
     , ('Scooby Doo: Mystery Mayhem', 1)
     , ('Scooby-Doo! Night of 100 Frights', 1)
     , ('Scooby-Doo! Unmasked', 1)
     , ('The Scorpion King: Rise of the Akkadian', 1)
     , ('SD Gundam Gashapon Wars', 1)
     , ('Sea World: Shamu''s Deep Sea Adventures', 1)
     , ('Second Sight', 1)
     , ('Sega Soccer Slam', 1)
     , ('Serious Sam: Next Encounter', 1)
     , ('Shadow the Hedgehog', 1)
     , ('Shaman King: Soul Fight', 1)
     , ('Shark Tale', 1)
     , ('Shikigami no Shiro II', 1)
     , ('Shinseiki GPX Cyber Formula: Road to the Evolution', 1)
     , ('Shrek 2', 1)
     , ('Shrek Extra Large', 1)
     , ('Shrek Smash n'' Crash Racing', 1)
     , ('Shrek: Super Party', 1)
     , ('Shrek SuperSlam', 1)
     , ('The Simpsons: Hit &amp; Run', 1)
     , ('The Simpsons: Road Rage', 1)
     , ('The Sims', 1)
     , ('The Sims 2', 1)
     , ('The Sims 2: Pets', 1)
     , ('The Sims Bustin'' Out', 1)
     , ('Skies of Arcadia Legends', 1)
     , ('Smashing Drive', 1)
     , ('Smuggler''s Run: Warzones', 1)
     , ('Sonic Adventure DX: Director''s Cut', 1)
     , ('Sonic Adventure 2: Battle', 1)
     , ('Sonic Gems Collection', 1)
     , ('Sonic Heroes', 1)
     , ('Sonic Mega Collection', 1)
     , ('Sonic Riders', 1)
     , ('Soulcalibur II', 1)
     , ('Space Raiders', 1)
     , ('Spartan: Total Warrior', 1)
     , ('Spawn: Armageddon', 1)
     , ('Special Jinsei Game', 1)
     , ('Speed Challenge: Jacques Villeneuve''s Racing Vision', 1)
     , ('Speed Kings', 1)
     , ('Sphinx and the Cursed Mummy', 1)
     , ('Spider-Man', 1)
     , ('Spider-Man 2', 1)
     , ('Spirits &amp; Spells', 1)
     , ('SpongeBob SquarePants: Battle for Bikini Bottom', 1)
     , ('SpongeBob SquarePants: Creature from the Krusty Krab', 1)
     , ('SpongeBob SquarePants: Lights, Camera, Pants!', 1)
     , ('The SpongeBob SquarePants Movie', 1)
     , ('SpongeBob SquarePants: Revenge of the Flying Dutchman', 1)
     , ('Spy Hunter', 1)
     , ('Spyro: A Hero''s Tail', 1)
     , ('Spyro: Enter the Dragonfly', 1)
     , ('SSX 3', 1)
     , ('SSX on Tour', 1)
     , ('SSX Tricky', 1)
     , ('Star Fox Adventures', 1)
     , ('Star Fox: Assault', 1)
     , ('Star Wars: Bounty Hunter', 1)
     , ('Star Wars Jedi Knight II: Jedi Outcast', 1)
     , ('Star Wars Rogue Squadron II: Rogue Leader', 1)
     , ('Star Wars Rogue Squadron III: Rebel Strike', 1)
     , ('Star Wars: The Clone Wars', 1)
     , ('Starsky &amp; Hutch', 1)
     , ('Street Hoops', 1)
     , ('Street Racing Syndicate', 1)
     , ('Strike Force Bowling', 1)
     , ('The Sum of All Fears', 1)
     , ('Summoner: A Goddess Reborn', 1)
     , ('Super Bubble Pop', 1)
     , ('Super Mario Strikers', 1)
     , ('Super Mario Sunshine', 1)
     , ('Super Monkey Ball', 1)
     , ('Super Monkey Ball 2', 1)
     , ('Super Monkey Ball Adventure', 1)
     , ('Super Robot Wars GC', 1)
     , ('Super Smash Bros. Melee', 1)
     , ('Superman: Shadow of Apokolips', 1)
     , ('Surf''s Up', 1)
     , ('Swingerz Golf', 1)
     , ('SX Superstar', 1)
     , ('Tak and the Power of Juju', 1)
     , ('Tak: The Great Juju Challenge', 1)
     , ('Tak 2: The Staff of Dreams', 1)
     , ('Tales of Symphonia', 1)
     , ('Taxi 3', 1)
     , ('Taz: Wanted', 1)
     , ('Teen Titans', 1)
     , ('Teenage Mutant Ninja Turtles', 1)
     , ('Teenage Mutant Ninja Turtles 2: Battle Nexus', 1)
     , ('Teenage Mutant Ninja Turtles 3: Mutant Nightmare', 1)
     , ('Tengai Makyō II: Manjimaru', 1)
     , ('Tensai Bit-Kun: Gramon Battle', 1)
     , ('Terminator 3: The Redemption', 1)
     , ('Tetris Worlds', 1)
     , ('Tiger Woods PGA Tour 2003', 1)
     , ('Tiger Woods PGA Tour 2004', 1)
     , ('Tiger Woods PGA Tour 2005', 1)
     , ('Tiger Woods PGA Tour 06', 1)
     , ('TimeSplitters 2', 1)
     , ('TimeSplitters: Future Perfect', 1)
     , ('TMNT', 1)
     , ('TMNT: Mutant Melee', 1)
     , ('Tom and Jerry: War of the Whiskers', 1)
     , ('Tom Clancy''s Ghost Recon', 1)
     , ('Tom Clancy''s Ghost Recon 2', 1)
     , ('Tom Clancy''s Rainbow Six 3: Raven Shield', 1)
     , ('Tom Clancy''s Rainbow Six: Lockdown', 1)
     , ('Tom Clancy''s Splinter Cell', 1)
     , ('Tom Clancy''s Splinter Cell: Chaos Theory', 1)
     , ('Tom Clancy''s Splinter Cell: Double Agent', 1)
     , ('Tom Clancy''s Splinter Cell: Pandora Tomorrow', 1)
     , ('Tomb Raider: Legend', 1)
     , ('Tonka: Rescue Patrol', 1)
     , ('Tony Hawk''s American Wasteland', 1)
     , ('Tony Hawk''s Pro Skater 3', 1)
     , ('Tony Hawk''s Pro Skater 4', 1)
     , ('Tony Hawk''s Underground', 1)
     , ('Tony Hawk''s Underground 2', 1)
     , ('Top Angler: Real Bass Fishing', 1)
     , ('Top Gun: Combat Zones', 1)
     , ('The Tower of Druaga', 1)
     , ('TransWorld Surf: Next Wave', 1)
     , ('Trigger Man', 1)
     , ('True Crime: New York City', 1)
     , ('True Crime: Streets of LA', 1)
     , ('Tube Slider', 1)
     , ('Turok: Evolution', 1)
     , ('Ty the Tasmanian Tiger', 1)
     , ('Ty the Tasmanian Tiger 2: Bush Rescue', 1)
     , ('Ty the Tasmanian Tiger 3: Night of the Quinkan', 1)
     , ('UEFA Champions League 2004-2005', 1)
     , ('Ultimate Fighting Championship: Throwdown', 1)
     , ('Ultimate Muscle: Legends vs. New Generation', 1)
     , ('Ultimate Spider-Man', 1)
     , ('Universal Studios Theme Parks Adventure', 1)
     , ('The Urbz: Sims in the City', 1)
     , ('V-Rally 3', 1)
     , ('Vexx', 1)
     , ('Viewtiful Joe', 1)
     , ('Viewtiful Joe 2', 1)
     , ('Viewtiful Joe: Red Hot Rumble', 1)
     , ('Virtua Quest', 1)
     , ('Virtua Striker 2002', 1)
     , ('Wallace &amp; Gromit in Project Zoo', 1)
     , ('Wario World', 1)
     , ('WarioWare, Inc.: Mega Party Game$', 1)
     , ('Warrior Blade: Rastan vs. Barbarian', 1)
     , ('Wave Race: Blue Storm', 1)
     , ('Whirl Tour', 1)
     , ('Winnie the Pooh''s Rumbly Tumbly Adventure', 1)
     , ('World Series of Poker', 1)
     , ('World Soccer Winning Eleven 6 Final Evolution', 1)
     , ('Worms 3D', 1)
     , ('Worms Blast', 1)
     , ('Wreckless: The Yakuza Missions', 1)
     , ('WTA Tour Tennis', 1)
     , ('WWE Crush Hour', 1)
     , ('WWE Day of Reckoning', 1)
     , ('WWE Day of Reckoning 2', 1)
     , ('WWE WrestleMania X8', 1)
     , ('WWE WrestleMania XIX', 1)
     , ('X-Men Legends', 1)
     , ('X-Men Legends II: Rise of Apocalypse', 1)
     , ('X-Men: Next Dimension', 1)
     , ('X-Men: The Official Game', 1)
     , ('X2: Wolverine''s Revenge', 1)
     , ('XGRA: Extreme-G Racing Association', 1)
     , ('XIII', 1)
     , ('Yu-Gi-Oh! The Falsebound Kingdom', 1)
     , ('Zapper: One Wicked Cricket', 1)
     , ('Zatch Bell! Mamodo Battles', 1)
     , ('Zatch Bell! Mamodo Fury', 1)
     , ('Zoids Vs.', 1)
     , ('Zoids Vs. III', 1)
     , ('Zoids: Battle Legends', 1)
     , ('Zoids: Full Metal Crash', 1)
     , ('ZooCube', 1)
     , ('Mario Kart: Double Dash!! Bonus Disc', 1)
     , ('Metroid Prime 2: Echoes Bonus Disc', 1)
     , ('Nintendo GameCube Preview Disc', 1)
     , ('Pokémon Colosseum Bonus Disc', 1)
     , ('Star Wars Rogue Squadron III: Rebel Strike Preview Disc', 1)
     ;
