-- https://en.wikipedia.org/wiki/List_of_Xbox_games

INSERT INTO platforms(id, name)
VALUES (2, 'Xbox');

INSERT INTO games(name, platform_id)
VALUES ('007: Agent Under Fire', 2)
     , ('007: Everything or Nothing', 2)
     , ('007: From Russia with Love', 2)
     , ('007: Nightfire', 2)
     , ('187 Ride or Die', 2)
     , ('2002 FIFA World Cup', 2)
     , ('2006 FIFA World Cup', 2)
     , ('25 To Life', 2)
     , ('4x4 EVO 2', 2)
     , ('50 Cent: Bulletproof', 2)
     , ('Advent Rising', 2)
     , ('Æon Flux', 2)
     , ('AFL Live 2003', 2)
     , ('AFL Live 2004', 2)
     , ('AFL Live Premiership Edition', 2)
     , ('AFL Premiership 2005', 2)
     , ('Aggressive Inline', 2)
     , ('Airforce Delta Storm', 2)
     , ('Alias', 2)
     , ('Alien Hominid', 2)
     , ('Aliens Versus Predator: Extinction', 2)
     , ('Alfa Romeo Racing Italiano', 2)
     , ('All-Star Baseball 2003', 2)
     , ('All-Star Baseball 2004', 2)
     , ('All-Star Baseball 2005', 2)
     , ('Alter Echo', 2)
     , ('America''s Army: Rise of a Soldier', 2)
     , ('American Chopper', 2)
     , ('American Chopper 2: Full Throttle', 2)
     , ('AMF Bowling 2004', 2)
     , ('AMF Xtreme Bowling 2006', 2)
     , ('Amped: Freestyle Snowboarding', 2)
     , ('Amped 2', 2)
     , ('AND 1 Streetball', 2)
     , ('Animaniacs: The Great Edgar Hunt', 2)
     , ('Antz Extreme Racing', 2)
     , ('APEX', 2)
     , ('Aquaman: Battle for Atlantis', 2)
     , ('Arctic Thunder', 2)
     , ('Area 51', 2)
     , ('Arena Football', 2)
     , ('Armed and Dangerous', 2)
     , ('Army Men: Major Malfunction', 2)
     , ('Army Men: Sarge''s War', 2)
     , ('Arx Fatalis', 2)
     , ('Atari Anthology', 2)
     , ('ATV Quad Power Racing 2', 2)
     , ('Auto Modellista', 2)
     , ('Avatar: The Last Airbender', 2)
     , ('Azurik: Rise of Perathia', 2)
     , ('Backyard Wrestling: Don''t Try This at Home', 2)
     , ('Backyard Wrestling 2: There Goes the Neighborhood', 2)
     , ('Bad Boys: Miami Takedown', 2)
     , ('Baldur''s Gate: Dark Alliance', 2)
     , ('Baldur''s Gate: Dark Alliance II', 2)
     , ('Barbarian', 2)
     , ('Barbie Horse Adventures: Wild Horse Rescue', 2)
     , ('The Bard''s Tale', 2)
     , ('Bass Pro Shops Trophy Hunter 2007', 2)
     , ('Batman Begins', 2)
     , ('Batman: Dark Tomorrow', 2)
     , ('Batman: Rise of Sin Tzu', 2)
     , ('Batman Vengeance', 2)
     , ('Battle Engine Aquila', 2)
     , ('Battlefield 2: Modern Combat', 2)
     , ('Battlestar Galactica', 2)
     , ('Beat Down: Fists of Vengeance', 2)
     , ('Beyond Good &amp; Evil', 2)
     , ('The Bible Game', 2)
     , ('Bicycle Casino', 2)
     , ('Big Bumpin''', 2)
     , ('Big Mutha Truckers', 2)
     , ('Big Mutha Truckers 2', 2)
     , ('Bionicle', 2)
     , ('Black', 2)
     , ('Black Stone: Magic &amp; Steel', 2)
     , ('Blade II (video game)', 2)
     , ('Blazing Angels: Squadrons of WWII', 2)
     , ('Blinx: The Time Sweeper', 2)
     , ('Blinx 2: Masters of Time and Space', 2)
     , ('Blitz: The League', 2)
     , ('Blood Omen 2', 2)
     , ('Blood Wake', 2)
     , ('BloodRayne', 2)
     , ('BloodRayne 2', 2)
     , ('Bloody Roar Extreme', 2)
     , ('BlowOut', 2)
     , ('BMX XXX', 2)
     , ('Breakdown', 2)
     , ('Breeders'' Cup World Thoroughbred Championships', 2)
     , ('Brian Lara International Cricket 2005', 2)
     , ('Broken Sword: The Sleeping Dragon', 2)
     , ('Brothers in Arms: Earned in Blood', 2)
     , ('Brothers in Arms: Road to Hill 30', 2)
     , ('Bruce Lee: Quest of the Dragon', 2)
     , ('Brute Force', 2)
     , ('Buffy the Vampire Slayer', 2)
     , ('Buffy the Vampire Slayer: Chaos Bleeds', 2)
     , ('Burnout', 2)
     , ('Burnout 2: Point of Impact', 2)
     , ('Burnout 3: Takedown', 2)
     , ('Burnout Revenge', 2)
     , ('C.A.T.: Cyber Attack Team', 2)
     , ('Cabela''s Big Game Hunter 2005 Adventures', 2)
     , ('Cabela''s Dangerous Hunts', 2)
     , ('Cabela''s Dangerous Hunts 2', 2)
     , ('Cabela''s Deer Hunt: 2004 Season', 2)
     , ('Cabela''s Deer Hunt: 2005 Season', 2)
     , ('Cabela''s Outdoor Adventures', 2)
     , ('Call of Cthulhu: Dark Corners of the Earth', 2)
     , ('Call of Duty: Finest Hour', 2)
     , ('Call of Duty 2: Big Red One', 2)
     , ('Call of Duty 3', 2)
     , ('Capcom Classics Collection Vol. 1', 2)
     , ('Capcom Classics Collection Vol. 2', 2)
     , ('Capcom Fighting Evolution', 2)
     , ('Capcom vs. SNK 2 EO', 2)
     , ('Carmen Sandiego: The Secret of the Stolen Drums', 2)
     , ('Cars', 2)
     , ('Carve', 2)
     , ('Castlevania: Curse of Darkness', 2)
     , ('Catwoman', 2)
     , ('Cel Damage', 2)
     , ('Celebrity Deathmatch', 2)
     , ('Championship Bowling', 2)
     , ('Championship Manager: Season 01/02', 2)
     , ('Championship Manager: Season 02/03', 2)
     , ('Championship Manager 2006', 2)
     , ('Championship Manager 5', 2)
     , ('Charlie and the Chocolate Factory', 2)
     , ('Chase: Hollywood Stunt Driver', 2)
     , ('Chessmaster 10th Edition', 2)
     , ('Chicago Enforcer', 2)
     , ('Chicken Little', 2)
     , ('The Chronicles of Narnia: The Lion, the Witch and the Wardrobe', 2)
     , ('The Chronicles of Riddick: Escape from Butcher Bay', 2)
     , ('Circus Maximus: Chariot Wars', 2)
     , ('Classified: The Sentinel Crisis', 2)
     , ('Close Combat: First to Fight', 2)
     , ('Club Football', 2)
     , ('Club Football 2005', 2)
     , ('Codename: Kids Next Door - Operation: V.I.D.E.O.G.A.M.E.', 2)
     , ('Cold Fear', 2)
     , ('Cold War', 2)
     , ('Colin McRae Rally 04', 2)
     , ('Colin McRae Rally 2005', 2)
     , ('Colin McRae Rally 3', 2)
     , ('College Hoops 2K6', 2)
     , ('College Hoops 2K7', 2)
     , ('Combat Elite: WWII Paratroopers', 2)
     , ('Commandos: Strike Force', 2)
     , ('Commandos 2: Men of Courage', 2)
     , ('Conan', 2)
     , ('Conflict: Desert Storm', 2)
     , ('Conflict: Desert Storm II: Back to Baghdad', 2)
     , ('Conflict: Global Terror', 2)
     , ('Conflict: Vietnam', 2)
     , ('Conker: Live &amp; Reloaded', 2)
     , ('Constantine', 2)
     , ('Corvette', 2)
     , ('Counter-Strike', 2)
     , ('Crash Bandicoot: The Wrath of Cortex', 2)
     , ('Crash ''n'' Burn', 2)
     , ('Crash Nitro Kart', 2)
     , ('Crash Tag Team Racing', 2)
     , ('Crash Twinsanity', 2)
     , ('Crazy Taxi 3: High Roller', 2)
     , ('Cricket 2005', 2)
     , ('Crime Life: Gang Wars', 2)
     , ('Crimson Sea', 2)
     , ('Crimson Skies: High Road to Revenge', 2)
     , ('Crouching Tiger, Hidden Dragon', 2)
     , ('CSI: Crime Scene Investigation', 2)
     , ('Curious George', 2)
     , ('Curse: The Eye of Isis', 2)
     , ('The Da Vinci Code', 2)
     , ('Dai Senryaku VII: Modern Military Tactics', 2)
     , ('Dakar 2: The World''s Ultimate Rally', 2)
     , ('Dance Dance Revolution Ultramix', 2)
     , ('Dance Dance Revolution Ultramix 2', 2)
     , ('Dance Dance Revolution Ultramix 3', 2)
     , ('Dance Dance Revolution Ultramix 4', 2)
     , ('Dark Summit', 2)
     , ('Darkwatch', 2)
     , ('Dave Mirra Freestyle BMX 2', 2)
     , ('David Beckham Soccer', 2)
     , ('Dead Man''s Hand', 2)
     , ('Dead or Alive 3', 2)
     , ('Dead or Alive Ultimate', 2)
     , ('Dead or Alive Xtreme Beach Volleyball', 2)
     , ('Dead to Rights', 2)
     , ('Dead to Rights II', 2)
     , ('Deathrow', 2)
     , ('Def Jam: Fight for NY', 2)
     , ('Defender', 2)
     , ('Delta Force: Black Hawk Down', 2)
     , ('Destroy All Humans!', 2)
     , ('Destroy All Humans! 2', 2)
     , ('Deus Ex: Invisible War', 2)
     , ('Die Hard: Vendetta', 2)
     , ('Digimon Rumble Arena 2', 2)
     , ('Digimon World 4', 2)
     , ('Dino Crisis 3', 2)
     , ('Dinotopia: The Sunstone Odyssey', 2)
     , ('Disney''s Extreme Skate Adventure', 2)
     , ('Doom 3', 2)
     , ('Doom 3: Resurrection of Evil', 2)
     , ('Dr. Muto', 2)
     , ('Dr. Seuss'' The Cat in the Hat', 2)
     , ('Dragon Ball Z: Sagas', 2)
     , ('Dragon''s Lair 3D: Return to the Lair', 2)
     , ('Drake of the 99 Dragons', 2)
     , ('Dreamfall: The Longest Journey', 2)
     , ('DRIV3R', 2)
     , ('Driver: Parallel Lines', 2)
     , ('The Dukes of Hazzard: Return of the General Lee', 2)
     , ('Dungeons &amp; Dragons: Heroes', 2)
     , ('Dynasty Warriors 3', 2)
     , ('Dynasty Warriors 4', 2)
     , ('Dynasty Warriors 5', 2)
     , ('Ed, Edd n Eddy: The Mis-Edventures', 2)
     , ('Egg Mania: Eggstreme Madness', 2)
     , ('The Elder Scrolls III: Morrowind', 2)
     , ('Enclave', 2)
     , ('Enter the Matrix', 2)
     , ('Eragon', 2)
     , ('ESPN College Hoops', 2)
     , ('ESPN College Hoops 2K5', 2)
     , ('ESPN International Winter Sports 2002', 2)
     , ('ESPN MLS ExtraTime 2002', 2)
     , ('ESPN NBA 2K5', 2)
     , ('ESPN NBA 2Night 2002', 2)
     , ('ESPN NBA Basketball', 2)
     , ('ESPN NFL 2K5', 2)
     , ('ESPN NFL Football', 2)
     , ('ESPN NHL 2K5', 2)
     , ('ESPN NHL Hockey', 2)
     , ('Evil Dead: A Fistful of Boomstick', 2)
     , ('Evil Dead: Regeneration', 2)
     , ('F1 2001', 2)
     , ('F1 2002', 2)
     , ('F1 Career Challenge', 2)
     , ('Fable', 2)
     , ('Fable: The Lost Chapters', 2)
     , ('The Fairly OddParents: Breakin'' Da Rules', 2)
     , ('Fallout: Brotherhood of Steel', 2)
     , ('Family Guy Video Game!', 2)
     , ('Fantastic 4', 2)
     , ('Far Cry Instincts', 2)
     , ('Far Cry Instincts: Evolution', 2)
     , ('Fatal Frame', 2)
     , ('Fatal Frame II: Crimson Butterfly', 2)
     , ('FIFA 06 Soccer', 2)
     , ('FIFA 07', 2)
     , ('FIFA Football 2003', 2)
     , ('FIFA Football 2004', 2)
     , ('FIFA 2005', 2)
     , ('FIFA Street', 2)
     , ('FIFA Street 2', 2)
     , ('FIFA World Cup: Germany 2006', 2)
     , ('Fight Club', 2)
     , ('Fight Night 2004', 2)
     , ('Fight Night Round 2', 2)
     , ('Fight Night: Round 3', 2)
     , ('Final Fight: Streetwise', 2)
     , ('Finding Nemo', 2)
     , ('Fire Blade', 2)
     , ('FlatOut', 2)
     , ('FlatOut 2', 2)
     , ('Ford Bold Moves Street Racing', 2)
     , ('Ford Mustang: The Legend Lives', 2)
     , ('Ford Racing 2', 2)
     , ('Ford Racing 3', 2)
     , ('Ford vs. Chevy', 2)
     , ('Forgotten Realms: Demon Stone', 2)
     , ('Forza Motorsport', 2)
     , ('Freaky Flyers', 2)
     , ('Freedom Fighters', 2)
     , ('Freestyle MetalX', 2)
     , ('Freestyle Street Soccer', 2)
     , ('Frogger Beyond', 2)
     , ('Frogger: Ancient Shadow', 2)
     , ('Full Spectrum Warrior', 2)
     , ('Full Spectrum Warrior: Ten Hammers', 2)
     , ('Futurama', 2)
     , ('Future Tactics: The Uprising', 2)
     , ('Fuzion Frenzy', 2)
     , ('Galaxy Angel', 2)
     , ('Galleon', 2)
     , ('Gauntlet: Dark Legacy', 2)
     , ('Gauntlet: Seven Sorrows', 2)
     , ('Genma Onimusha', 2)
     , ('Ghost Master: The Gravenville Chronicles', 2)
     , ('Gladiator: Sword of Vengeance', 2)
     , ('Gladius', 2)
     , ('Goblin Commander: Unleash the Horde', 2)
     , ('The Godfather: The Game', 2)
     , ('Godzilla: Destroy All Monsters Melee', 2)
     , ('Godzilla: Save the Earth', 2)
     , ('GoldenEye: Rogue Agent', 2)
     , ('Gotcha!', 2)
     , ('Grabbed by the Ghoulies', 2)
     , ('Grand Theft Auto III', 2)
     , ('Grand Theft Auto: San Andreas', 2)
     , ('Grand Theft Auto: Vice City', 2)
     , ('Gravity Games Bike: Street. Vert. Dirt.', 2)
     , ('The Great Escape', 2)
     , ('Greg Hastings Tournament Paintball', 2)
     , ('Greg Hastings'' Tournament Paintball Max''d', 2)
     , ('Grooverider: Slot Car Thunder', 2)
     , ('Group S Challenge', 2)
     , ('Guilty Gear Isuka', 2)
     , ('Guilty Gear X2#Reload', 2)
     , ('Gun', 2)
     , ('Gun Metal', 2)
     , ('GunGriffon: Allied Strike', 2)
     , ('Gunvalkyrie', 2)
     , ('The Guy Game', 2)
     , ('Half-Life 2', 2)
     , ('Halo: Combat Evolved', 2)
     , ('Halo 2', 2)
     , ('Halo 2 Multiplayer Map Pack', 2)
     , ('Harry Potter and the Chamber of Secrets', 2)
     , ('Harry Potter and the Goblet of Fire', 2)
     , ('Harry Potter and the Prisoner of Azkaban', 2)
     , ('Harry Potter and the Sorcerer''s Stone', 2)
     , ('Harry Potter: Quidditch World Cup', 2)
     , ('The Haunted Mansion', 2)
     , ('Headhunter Redemption', 2)
     , ('Hello Kitty: Roller Rescue', 2)
     , ('Heroes of the Pacific', 2)
     , ('High Heat Major League Baseball 2004', 2)
     , ('High Rollers Casino', 2)
     , ('Hitman: Blood Money', 2)
     , ('Hitman: Contracts', 2)
     , ('Hitman 2: Silent Assassin', 2)
     , ('The Hobbit', 2)
     , ('Hot Wheels: Stunt Track Challenge', 2)
     , ('The House of the Dead III', 2)
     , ('Hulk', 2)
     , ('Hummer Badlands', 2)
     , ('Hunter: The Reckoning', 2)
     , ('Hunter: The Reckoning: Redeemer', 2)
     , ('I-Ninja', 2)
     , ('Ice Age 2: The Meltdown', 2)
     , ('IHRA Drag Racing 2004', 2)
     , ('IHRA Drag Racing: Sportsman Edition', 2)
     , ('IHRA Professional Drag Racing 2005', 2)
     , ('The Incredible Hulk: Ultimate Destruction', 2)
     , ('The Incredibles', 2)
     , ('The Incredibles: Rise of the Underminer', 2)
     , ('Indiana Jones and the Emperor''s Tomb', 2)
     , ('Indigo Prophecy', 2)
     , ('IndyCar Series', 2)
     , ('IndyCar Series 2005', 2)
     , ('The Italian Job', 2)
     , ('Intellivision Lives!', 2)
     , ('International Superstar Soccer 2', 2)
     , ('Jade Empire', 2)
     , ('James Cameron''s Dark Angel', 2)
     , ('Jaws Unleashed', 2)
     , ('Jet Set Radio Future', 2)
     , ('Jikkyou World Soccer 2002', 2)
     , ('Judge Dredd: Dredd Vs. Death', 2)
     , ('Juiced', 2)
     , ('Jurassic Park: Operation Genesis', 2)
     , ('Just Cause', 2)
     , ('Justice League Heroes', 2)
     , ('Kabuki Warriors', 2)
     , ('Kakuto Chojin', 2)
     , ('Kao the Kangaroo: Round 2', 2)
     , ('Karaoke Revolution', 2)
     , ('Karaoke Revolution Party', 2)
     , ('Kelly Slater''s Pro Surfer', 2)
     , ('Kill Switch', 2)
     , ('King Arthur', 2)
     , ('Kingdom Under Fire: Heroes', 2)
     , ('Kingdom Under Fire: The Crusaders', 2)
     , ('The King of Fighters 2002', 2)
     , ('The King of Fighters 2003', 2)
     , ('The King of Fighters Neowave', 2)
     , ('The King of Fighters: Maximum Impact', 2)
     , ('Knights of the Temple: Infernal Crusade', 2)
     , ('Knights of the Temple II', 2)
     , ('Knockout Kings 2002', 2)
     , ('Kung Fu Chaos', 2)
     , ('L.A. Rush', 2)
     , ('Land of the Dead: Road to Fiddler''s Green', 2)
     , ('Largo Winch: Empire Under Threat', 2)
     , ('Legacy of Kain: Defiance', 2)
     , ('The Legend of Spyro: A New Beginning', 2)
     , ('Legends of Wrestling', 2)
     , ('Legends of Wrestling II', 2)
     , ('Lego Star Wars: The Video Game', 2)
     , ('Lego Star Wars II: The Original Trilogy', 2)
     , ('Leisure Suit Larry: Magna Cum Laude', 2)
     , ('Lemony Snicket''s A Series of Unfortunate Events', 2)
     , ('Links 2004', 2)
     , ('LMA Manager 2003', 2)
     , ('LMA Manager 2004', 2)
     , ('LMA Manager 2005', 2)
     , ('LMA Manager 2006', 2)
     , ('Loons: The Fight for Fame', 2)
     , ('The Lord of the Rings: The Fellowship of the Ring', 2)
     , ('The Lord of the Rings: The Return of the King', 2)
     , ('The Lord of the Rings: The Third Age', 2)
     , ('The Lord of the Rings: The Two Towers', 2)
     , ('Lotus Challenge', 2)
     , ('Mace Griffin: Bounty Hunter', 2)
     , ('Mad Dash Racing', 2)
     , ('Madagascar', 2)
     , ('Madden NFL 06', 2)
     , ('Madden NFL 07', 2)
     , ('Madden NFL 08', 2)
     , ('Madden NFL 09', 2)
     , ('Madden NFL 2002', 2)
     , ('Madden NFL 2003', 2)
     , ('Madden NFL 2004', 2)
     , ('Madden NFL 2005', 2)
     , ('Mafia: The City of Lost Heaven', 2)
     , ('Magic the Gathering: Battlegrounds', 2)
     , ('Major League Baseball 2K5', 2)
     , ('Major League Baseball 2K5: World Series Edition', 2)
     , ('Major League Baseball 2K6', 2)
     , ('Major League Baseball 2K7', 2)
     , ('Malice', 2)
     , ('Manchester United Manager 2005', 2)
     , ('Manhunt', 2)
     , ('Marc Ecko''s Getting Up: Contents Under Pressure', 2)
     , ('Marvel: Ultimate Alliance', 2)
     , ('Marvel Nemesis: Rise of the Imperfects', 2)
     , ('Marvel vs. Capcom 2', 2)
     , ('Mashed: Drive to Survive', 2)
     , ('Mashed: Fully Loaded', 2)
     , ('Mat Hoffman''s Pro BMX 2', 2)
     , ('The Matrix: Path of Neo', 2)
     , ('Max Payne', 2)
     , ('Max Payne 2: The Fall of Max Payne', 2)
     , ('Maximum Chase', 2)
     , ('MechAssault', 2)
     , ('MechAssault 2: Lone Wolf', 2)
     , ('Medal of Honor: European Assault', 2)
     , ('Medal of Honor: Frontline', 2)
     , ('Medal of Honor: Rising Sun', 2)
     , ('Mega Man Anniversary Collection', 2)
     , ('Melbourne Cup Challenge', 2)
     , ('Men of Valor', 2)
     , ('Mercenaries: Playground of Destruction', 2)
     , ('Metal Arms: Glitch in the System', 2)
     , ('Metal Dungeon', 2)
     , ('Metal Gear Solid 2: Substance', 2)
     , ('Metal Slug 3', 2)
     , ('Metal Slug 4', 2)
     , ('Metal Slug 5', 2)
     , ('Metal Wolf Chaos', 2)
     , ('Micro Machines', 2)
     , ('Midnight Club II', 2)
     , ('Midnight Club 3: DUB Edition', 2)
     , ('Midnight Club 3: DUB Edition Remix', 2)
     , ('Midtown Madness 3', 2)
     , ('Midway Arcade Treasures', 2)
     , ('Midway Arcade Treasures 2', 2)
     , ('Midway Arcade Treasures 3', 2)
     , ('Minority Report: Everybody Runs', 2)
     , ('Mission Impossible: Operation Surma', 2)
     , ('MLB Slugfest 2003', 2)
     , ('MLB Slugfest 2004', 2)
     , ('MLB Slugfest 2006', 2)
     , ('MLB Slugfest: Loaded', 2)
     , ('Mojo!', 2)
     , ('Monopoly Party', 2)
     , ('Monster 4x4: World Circuit', 2)
     , ('Mortal Kombat: Armageddon', 2)
     , ('Mortal Kombat: Deadly Alliance', 2)
     , ('Mortal Kombat: Deception', 2)
     , ('Mortal Kombat: Shaolin Monks', 2)
     , ('Motocross Mania 3', 2)
     , ('MotoGP 2', 2)
     , ('MotoGP 3', 2)
     , ('MTX: Mototrax', 2)
     , ('Murakumo: Renegade Mech Pursuit', 2)
     , ('MVP 06: NCAA Baseball', 2)
     , ('MVP Baseball 2003', 2)
     , ('MVP Baseball 2004', 2)
     , ('MVP Baseball 2005', 2)
     , ('MX Superfly', 2)
     , ('MX Unleashed', 2)
     , ('MX vs. ATV Unleashed', 2)
     , ('Myst III: Exile', 2)
     , ('Myst IV: Revelation', 2)
     , ('N.U.D.E.@ Natural Ultimate Digital Experiment', 2)
     , ('Namco Museum', 2)
     , ('Namco Museum 50th Anniversary', 2)
     , ('Narc', 2)
     , ('NASCAR 06: Total Team Control', 2)
     , ('NASCAR 07', 2)
     , ('NASCAR 2005: Chase for the Cup', 2)
     , ('NASCAR Heat 2002', 2)
     , ('NASCAR Thunder 2002', 2)
     , ('NASCAR Thunder 2003', 2)
     , ('NASCAR Thunder 2004', 2)
     , ('NBA 2K2', 2)
     , ('NBA 2K3', 2)
     , ('NBA 2K6', 2)
     , ('NBA 2K7', 2)
     , ('NBA Ballers', 2)
     , ('NBA Ballers: Phenom', 2)
     , ('NBA Inside Drive 2002', 2)
     , ('NBA Inside Drive 2003', 2)
     , ('NBA Inside Drive 2004', 2)
     , ('NBA Jam', 2)
     , ('NBA Live 06', 2)
     , ('NBA Live 07', 2)
     , ('NBA Live 2002', 2)
     , ('NBA Live 2003', 2)
     , ('NBA Live 2004', 2)
     , ('NBA Live 2005', 2)
     , ('NBA Starting Five', 2)
     , ('NBA Street V3', 2)
     , ('NBA Street Vol. 2', 2)
     , ('NCAA College Basketball 2K3', 2)
     , ('NCAA College Football 2K3', 2)
     , ('NCAA Football 06', 2)
     , ('NCAA Football 07', 2)
     , ('NCAA Football 08', 2)
     , ('NCAA Football 2003', 2)
     , ('NCAA Football 2004', 2)
     , ('NCAA Football 2005', 2)
     , ('NCAA March Madness 06', 2)
     , ('NCAA March Madness 2004', 2)
     , ('NCAA March Madness 2005', 2)
     , ('Need for Speed: Carbon', 2)
     , ('Need for Speed: Hot Pursuit 2', 2)
     , ('Need for Speed: Most Wanted', 2)
     , ('Need for Speed: Underground', 2)
     , ('Need for Speed: Underground 2', 2)
     , ('Neighbours from Hell', 2)
     , ('New Legends', 2)
     , ('NFL 2K2', 2)
     , ('NFL 2K3', 2)
     , ('NFL Blitz 2002', 2)
     , ('NFL Blitz 2003', 2)
     , ('NFL Blitz Pro', 2)
     , ('NFL Fever 2002', 2)
     , ('NFL Fever 2003', 2)
     , ('NFL Fever 2004', 2)
     , ('NFL Head Coach', 2)
     , ('NFL Street', 2)
     , ('NFL Street 2', 2)
     , ('NHL 06', 2)
     , ('NHL 07', 2)
     , ('NHL 2002', 2)
     , ('NHL 2003', 2)
     , ('NHL 2004', 2)
     , ('NHL 2005', 2)
     , ('NHL 2K3', 2)
     , ('NHL 2K6', 2)
     , ('NHL 2K7', 2)
     , ('NHL Hitz 20-02', 2)
     , ('NHL Hitz 20-03', 2)
     , ('NHL Hitz Pro', 2)
     , ('NHL Rivals 2004', 2)
     , ('Nickelodeon Party Blast', 2)
     , ('NightCaster', 2)
     , ('NightCaster II: Equinox', 2)
     , ('Ninja Gaiden', 2)
     , ('Ninja Gaiden Black', 2)
     , ('Nobunaga no Yabou: Ranseiki', 2)
     , ('ObsCure', 2)
     , ('Oddworld: Munch''s Oddysee', 2)
     , ('Oddworld: Stranger''s Wrath', 2)
     , ('Open Season', 2)
     , ('Operation Flashpoint: Elite', 2)
     , ('Otogi: Myth of Demons', 2)
     , ('Otogi 2: Immortal Warriors', 2)
     , ('Outlaw Golf', 2)
     , ('Outlaw Golf 2', 2)
     , ('Outlaw Golf: 9 More Holes of X-Mas', 2)
     , ('Outlaw Golf: Holiday Golf', 2)
     , ('Outlaw Tennis', 2)
     , ('Outlaw Volleyball', 2)
     , ('Outlaw Volleyball: Red Hot', 2)
     , ('OutRun 2', 2)
     , ('OutRun 2006: Coast 2 Coast', 2)
     , ('Over the Hedge', 2)
     , ('Pac-Man World 2', 2)
     , ('Pac-Man World 3', 2)
     , ('Painkiller: Hell Wars', 2)
     , ('Panzer Dragoon Orta', 2)
     , ('Panzer Elite Action: Fields of Glory', 2)
     , ('Pariah', 2)
     , ('Peter Jackson''s King Kong', 2)
     , ('Phantasy Star Online Episode I &amp; II', 2)
     , ('Phantom Crash', 2)
     , ('Phantom Dust', 2)
     , ('Pinball Hall of Fame', 2)
     , ('Pirates of the Caribbean', 2)
     , ('Pirates: The Legend of Black Kat', 2)
     , ('Pitfall: The Lost Expedition', 2)
     , ('Playboy: The Mansion', 2)
     , ('PocketBike Racer', 2)
     , ('Pool Shark 2', 2)
     , ('Powerdrome', 2)
     , ('Predator: Concrete Jungle', 2)
     , ('Prince of Persia: The Sands of Time', 2)
     , ('Prince of Persia: The Two Thrones', 2)
     , ('Prince of Persia: Warrior Within', 2)
     , ('Prisoner of War', 2)
     , ('Pro Race Driver', 2)
     , ('Project Gotham Racing', 2)
     , ('Project Gotham Racing 2', 2)
     , ('Project Snowblind', 2)
     , ('ProStroke Golf: World Tour 2007', 2)
     , ('Psi-Ops: The Mindgate Conspiracy', 2)
     , ('Psychonauts', 2)
     , ('Psyvariar 2', 2)
     , ('Pulse Racer', 2)
     , ('Pump It Up: Exceed', 2)
     , ('The Punisher', 2)
     , ('Pure Pinball', 2)
     , ('Puyo Pop: Fever', 2)
     , ('Quantum Redshift', 2)
     , ('R: Racing Evolution', 2)
     , ('Rallisport Challenge', 2)
     , ('RalliSport Challenge 2', 2)
     , ('Rally Fusion: Race of Champions', 2)
     , ('Ratatouille', 2)
     , ('Rayman 3: Hoodlum Havoc', 2)
     , ('Rayman Arena', 2)
     , ('Raze''s Hell', 2)
     , ('Real World Golf', 2)
     , ('Red Dead Revolver', 2)
     , ('Red Faction II', 2)
     , ('Red Ninja: End of Honor', 2)
     , ('RedCard 20-03', 2)
     , ('Reign of Fire', 2)
     , ('Rent-A-Hero No. 1', 2)
     , ('Reservoir Dogs', 2)
     , ('Return to Castle Wolfenstein: Tides of War', 2)
     , ('Richard Burns Rally', 2)
     , ('RLH: Run Like Hell', 2)
     , ('RoadKill', 2)
     , ('Robin Hood: Defender of the Crown', 2)
     , ('RoboCop', 2)
     , ('Robot Wars: Extreme Destruction', 2)
     , ('Robotech: Battlecry', 2)
     , ('Robotech: Invasion', 2)
     , ('Robots', 2)
     , ('Rocky', 2)
     , ('Rocky: Legends', 2)
     , ('Rogue Ops', 2)
     , ('Rogue Trooper', 2)
     , ('RollerCoaster Tycoon', 2)
     , ('Rolling', 2)
     , ('Rugby 06', 2)
     , ('Rugby 2005', 2)
     , ('Rugby Challenge 2006', 2)
     , ('Rugby League', 2)
     , ('Rugby League 2', 2)
     , ('Samurai Shodown V', 2)
     , ('Samurai Warriors', 2)
     , ('Scaler', 2)
     , ('Scarface: The World Is Yours', 2)
     , ('Scooby-Doo! Mystery Mayhem', 2)
     , ('Scooby-Doo! Night of 100 Frights', 2)
     , ('Scooby-Doo! Unmasked', 2)
     , ('American McGee Presents: Scrapland', 2)
     , ('SeaBlade', 2)
     , ('SeaWorld: Shamu''s Deep Sea Adventures', 2)
     , ('Second Sight', 2)
     , ('Secret Weapons Over Normandy', 2)
     , ('Sega GT 2002', 2)
     , ('Sega GT Online', 2)
     , ('Sega Soccer Slam', 2)
     , ('Sensible Soccer 2006', 2)
     , ('Serious Sam', 2)
     , ('Serious Sam 2', 2)
     , ('Shadow of Memories', 2)
     , ('Shadow Ops: Red Mercury', 2)
     , ('Shadow the Hedgehog', 2)
     , ('Shark Tale', 2)
     , ('Shattered Union', 2)
     , ('Shellshock: Nam ''67', 2)
     , ('Shenmue II', 2)
     , ('Shikigami no Shiro', 2)
     , ('Shikigami no Shiro Evolution Blue', 2)
     , ('Shikigami no Shiro Evolution Red', 2)
     , ('Shikigami no Shiro II', 2)
     , ('Shin Megami Tensei: Nine', 2)
     , ('Showdown: Legends of Wrestling', 2)
     , ('Shrek', 2)
     , ('Shrek 2', 2)
     , ('Shrek Super Party', 2)
     , ('Shrek SuperSlam', 2)
     , ('Sid Meier''s Pirates!', 2)
     , ('Silent Hill 2', 2)
     , ('Silent Hill 4: The Room', 2)
     , ('Silent Scope Complete', 2)
     , ('The Simpsons: Hit &amp; Run', 2)
     , ('The Simpsons: Road Rage', 2)
     , ('The Sims', 2)
     , ('The Sims 2', 2)
     , ('The Sims Bustin'' Out', 2)
     , ('Smashing Drive', 2)
     , ('Sneak King', 2)
     , ('Sneakers', 2)
     , ('Sniper Elite', 2)
     , ('Soldier of Fortune II: Double Helix', 2)
     , ('Sonic Heroes', 2)
     , ('Sonic Mega Collection Plus', 2)
     , ('Sonic Riders', 2)
     , ('Soul Calibur II', 2)
     , ('Spartan: Total Warrior', 2)
     , ('Spawn: Armageddon', 2)
     , ('Special Forces: Nemesis Strike', 2)
     , ('Speed Kings', 2)
     , ('Sphinx and the Cursed Mummy', 2)
     , ('Spider-Man', 2)
     , ('Spider-Man 2', 2)
     , ('Spikeout: Battle Street', 2)
     , ('Splashdown', 2)
     , ('Splat Magazine Renegade Paintball', 2)
     , ('SpongeBob SquarePants: Battle for Bikini Bottom', 2)
     , ('SpongeBob SquarePants: Lights, Camera, Pants!', 2)
     , ('The SpongeBob SquarePants Movie Game', 2)
     , ('Spy Hunter', 2)
     , ('Spy Hunter 2', 2)
     , ('Spy Hunter: Nowhere to Run', 2)
     , ('Spy vs. Spy', 2)
     , ('Spyro: A Hero''s Tail', 2)
     , ('SSX 3', 2)
     , ('SSX On Tour', 2)
     , ('SSX Tricky', 2)
     , ('Stacked with Daniel Negreanu', 2)
     , ('Stake: Fortune Fighters', 2)
     , ('Star Trek: Shattered Universe', 2)
     , ('Star Wars: Jedi Knight: Jedi Academy', 2)
     , ('Star Wars: Jedi Knight II: Jedi Outcast', 2)
     , ('Star Wars: Battlefront', 2)
     , ('Star Wars: Battlefront II', 2)
     , ('Star Wars: Episode III: Revenge of the Sith', 2)
     , ('Star Wars: Jedi Starfighter', 2)
     , ('Star Wars: Knights of the Old Republic', 2)
     , ('Star Wars: Knights of the Old Republic II: The Sith Lords', 2)
     , ('Star Wars: Obi-Wan', 2)
     , ('Star Wars: Republic Commando', 2)
     , ('Star Wars: Starfighter', 2)
     , ('Star Wars: The Clone Wars', 2)
     , ('Starsky &amp; Hutch', 2)
     , ('State of Emergency', 2)
     , ('Steel Battalion', 2)
     , ('Steel Battalion: Line of Contact', 2)
     , ('Still Life', 2)
     , ('Stolen', 2)
     , ('Street Fighter Anniversary Collection', 2)
     , ('Street Hoops', 2)
     , ('Street Racing Syndicate', 2)
     , ('Strike Force Bowling', 2)
     , ('Stubbs the Zombie in Rebel Without a Pulse', 2)
     , ('Sudeki', 2)
     , ('The Suffering', 2)
     , ('The Suffering: Ties That Bind', 2)
     , ('Super Bubble Pop', 2)
     , ('Super Monkey Ball Deluxe', 2)
     , ('Superman Returns', 2)
     , ('Superman: The Man of Steel', 2)
     , ('SVC Chaos: SNK vs. Capcom', 2)
     , ('SWAT: Global Strike Team', 2)
     , ('SX Superstar', 2)
     , ('Syberia', 2)
     , ('Syberia II', 2)
     , ('Taito Legends', 2)
     , ('Taito Legends 2', 2)
     , ('Tak: The Great Juju Challenge', 2)
     , ('Tak 2: The Staff of Dreams', 2)
     , ('Tao Feng: Fist of the Lotus', 2)
     , ('Taz: Wanted', 2)
     , ('Tecmo Classic Arcade', 2)
     , ('Teen Titans', 2)
     , ('Teenage Mutant Ninja Turtles', 2)
     , ('Teenage Mutant Ninja Turtles: Mutant Melee', 2)
     , ('Teenage Mutant Ninja Turtles 2: Battle Nexus', 2)
     , ('Teenage Mutant Ninja Turtles 3: Mutant Nightmare', 2)
     , ('Tenchu: Return from Darkness', 2)
     , ('The Terminator: Dawn of Fate', 2)
     , ('Terminator 3: Rise of the Machines', 2)
     , ('Terminator 3: The Redemption', 2)
     , ('Test Drive', 2)
     , ('Test Drive: Eve of Destruction', 2)
     , ('Test Drive Off-Road Wide Open', 2)
     , ('Tetris Worlds', 2)
     , ('Tetris Worlds (Online Edition)', 2)
     , ('Thief: Deadly Shadows', 2)
     , ('The Thing', 2)
     , ('Thrillville', 2)
     , ('Tiger Woods PGA Tour 2003', 2)
     , ('Tiger Woods PGA Tour 2004', 2)
     , ('Tiger Woods PGA Tour 2005', 2)
     , ('Tiger Woods PGA Tour 06', 2)
     , ('Tiger Woods PGA Tour 07', 2)
     , ('Tim Burton''s The Nightmare Before Christmas: Oogie''s Revenge', 2)
     , ('TimeSplitters 2', 2)
     , ('TimeSplitters: Future Perfect', 2)
     , ('TOCA Race Driver 2: The Ultimate Racing Simulator', 2)
     , ('TOCA Race Driver 3', 2)
     , ('ToeJam &amp; Earl III: Mission to Earth', 2)
     , ('Tom and Jerry in War of the Whiskers', 2)
     , ('Tom Clancy''s Ghost Recon', 2)
     , ('Tom Clancy''s Ghost Recon 2', 2)
     , ('Tom Clancy''s Ghost Recon 2: Summit Strike', 2)
     , ('Tom Clancy''s Ghost Recon: Advanced Warfighter', 2)
     , ('Tom Clancy''s Ghost Recon: Island Thunder', 2)
     , ('Tom Clancy''s Rainbow Six 3', 2)
     , ('Tom Clancy''s Rainbow Six 3: Black Arrow', 2)
     , ('Tom Clancy''s Rainbow Six: Critical Hour', 2)
     , ('Tom Clancy''s Rainbow Six: Lockdown', 2)
     , ('Tom Clancy''s Splinter Cell', 2)
     , ('Tom Clancy''s Splinter Cell: Chaos Theory', 2)
     , ('Tom Clancy''s Splinter Cell: Double Agent', 2)
     , ('Tom Clancy''s Splinter Cell: Pandora Tomorrow', 2)
     , ('Tomb Raider: Legend', 2)
     , ('Tony Hawk''s American Wasteland', 2)
     , ('Tony Hawk''s Pro Skater 2x', 2)
     , ('Tony Hawk''s Pro Skater 3', 2)
     , ('Tony Hawk''s Pro Skater 4', 2)
     , ('Tony Hawk''s Project 8', 2)
     , ('Tony Hawk''s Underground', 2)
     , ('Tony Hawk''s Underground 2', 2)
     , ('Top Gear RPM Tuning', 2)
     , ('Top Spin Tennis', 2)
     , ('Torino 2006', 2)
     , ('Tork: Prehistoric Punk', 2)
     , ('Total Club Manager 2004', 2)
     , ('Total Club Manager 2005', 2)
     , ('Total Immersion Racing', 2)
     , ('Total Overdose: A Gunslinger''s Tale in Mexico', 2)
     , ('Totaled!', 2)
     , ('Toxic Grind', 2)
     , ('TransWorld Surf', 2)
     , ('Trigger Man', 2)
     , ('Trivial Pursuit Unhinged', 2)
     , ('Tron 2.0 Killer App', 2)
     , ('True Crime: New York City', 2)
     , ('True Crime: Streets of LA', 2)
     , ('Turok: Evolution', 2)
     , ('Ty the Tasmanian Tiger', 2)
     , ('Ty the Tasmanian Tiger 2: Bush Rescue', 2)
     , ('Ty the Tasmanian Tiger 3: Night of the Quinkan', 2)
     , ('UEFA Euro 2004', 2)
     , ('UFC: Tapout', 2)
     , ('UFC: Tapout 2', 2)
     , ('Ultimate Spider-Man', 2)
     , ('Ultra Bust-a-Move', 2)
     , ('Unreal Championship', 2)
     , ('Unreal Championship 2: The Liandri Conflict', 2)
     , ('Unreal II: The Awakening', 2)
     , ('Urban Chaos: Riot Response', 2)
     , ('The Urbz: Sims in the City', 2)
     , ('V-Rally 3', 2)
     , ('Van Helsing', 2)
     , ('Vexx', 2)
     , ('Vietcong: Purple Haze', 2)
     , ('Virtual Pool: Tournament Edition', 2)
     , ('Voodoo Vince', 2)
     , ('Wakeboarding Unleashed', 2)
     , ('Wallace &amp; Gromit in Project Zoo', 2)
     , ('Wallace &amp; Gromit: The Curse of the Were-Rabbit', 2)
     , ('Warpath', 2)
     , ('The Warriors', 2)
     , ('Whacked!', 2)
     , ('Whiplash', 2)
     , ('WinBack 2: Project Poseidon', 2)
     , ('Wings of War', 2)
     , ('Without Warning', 2)
     , ('World Championship Poker', 2)
     , ('World Championship Poker 2: Featuring Howard Lederer', 2)
     , ('World Championship Pool 2004', 2)
     , ('World Championship Rugby', 2)
     , ('World Racing', 2)
     , ('World Racing 2', 2)
     , ('World Series Baseball 2K2', 2)
     , ('World Series Baseball 2K3', 2)
     , ('World Series of Poker', 2)
     , ('World Soccer Winning Eleven 8 International', 2)
     , ('World Soccer Winning Eleven 9', 2)
     , ('World War II Combat: Iwo Jima', 2)
     , ('World War II Combat: Road to Berlin', 2)
     , ('Worms 3D', 2)
     , ('Worms 4: Mayhem', 2)
     , ('Worms Forts: Under Siege', 2)
     , ('Wrath Unleashed', 2)
     , ('Wreckless: The Yakuza Missions', 2)
     , ('WTA Tour Tennis', 2)
     , ('WWE Raw 2', 2)
     , ('WWE WrestleMania 21', 2)
     , ('WWF RAW', 2)
     , ('X-Men Legends', 2)
     , ('X-Men Legends II: Rise of Apocalypse', 2)
     , ('X-Men: Next Dimension', 2)
     , ('X-Men: The Official Game', 2)
     , ('X2: Wolverine''s Revenge', 2)
     , ('XGRA: Extreme-G Racing Association', 2)
     , ('Xiaolin Showdown', 2)
     , ('XIII', 2)
     , ('Xyanide', 2)
     , ('Yager', 2)
     , ('Yourself!Fitness', 2)
     , ('Yu-Gi-Oh! The Dawn of Destiny', 2)
     , ('Zapper: One Wicked Cricket', 2)
     ;
